# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2.1
jobs:
  test:
    docker:
      - image: cimg/go:1.20
    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run: go test -race -covermode=atomic -coverprofile=coverage.out ./...
      - run:
          name: Upload coverage to Codecov
          command: bash <(curl -s https://codecov.io/bash)

  release:
    docker:
      - image: cimg/go:1.20
    steps:
      - checkout
      - run: sudo apt-get update && sudo apt-get install -y upx
      - run: curl -sfL https://goreleaser.com/static/run | bash

workflows:
  main:
    jobs:
      - test
      - release:
          # Only run this job on git tag pushes
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-.*)*/
